---
sidebar: sidebar
permalink: task_dc_rubrik_cdm.html
keywords: data collector, Rubrik, 
summary: Configuring Rubrik CDM data collector.
---

= Rubrik CDM Data Collector
:hardbreaks:

:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead] 
Data Infrastructure Insights uses the Rubrik data collector to acquire inventory and performance data from Rubrik storage appliances.


== Terminology

Data Infrastructure Insights acquires the following inventory information from the Rubrik data collector. For each asset type acquired by Data Infrastructure Insights, the most common terminology used for this asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:


[cols=2*, options="header", cols"50,50"]
|===
|Vendor/Model Term | Data Infrastructure Insights Term
|Cluster|Storage, Storage Pool
|Node|Storage Node
|Disk|Disk
|===

Note: These are common terminology mappings only and might not represent every case for this data source.




== Requirements

The following are required to configure this data collector:

* The Data Infrastructure Insights Acquisition Unit will initiate connections to TCP port 443 to Rubrik cluster. One collector per cluster.
* Rubrik cluster IP address.
* User name and password to the cluster.
* Rubrik cluster IP address or hostname.
* For Basic Authentication, a user name and password to the cluster. If you prefer to use Service Account based authentication, you need a Service Account, Secret, and an Organization ID
* Port requirement: HTTPS 443


== Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field | Description

|IP|IP address of the Rubrik cluster
|Username / Service account|User name for the cluster
|Password / Secret |Password for the cluster
|Organization ID for the service-account|This needs to be the full string like "Organization:::nnnnnn-nnnn....."
|===

== Advanced configuration 

[cols=2*, options="header", cols"50,50"]
|===
|Inventory poll interval (min)|The default is 60
|Performance Poll Interval (sec)|The default is 300
|===

           
== Troubleshooting
Some things to try if you encounter problems with this data collector:

=== Inventory

[cols=2*, options="header", cols"50,50"]
|===
|Problem:|Try this:
|I received a message that more than one storage is created.
|Check that the cluster is configured correctly, and the collector is pointing to a single cluster.
|Poll fails with 400 [Bad Request]....Invalid ManagedId....
|You have populated the Organization ID field with a value, but the Rubrik cluster does NOT believe that is a valid Organization ID, despite the error message from Rubrik referring to it as a "ManagedId"
|===

Additional information may be found from the link:concept_requesting_support.html[Support] page or in the link:reference_data_collector_support_matrix.html[Data Collector Support Matrix].
